import { Blocks, HandCoins, Radio, User } from "lucide-react";

import {
  lorelei,
  adventurer,
  adventurerNeutral,
  avataaars,
  avataaarsNeutral,
  bigEars,
  bigEarsNeutral,
  bigSmile,
  bottts,
  botttsNeutral,
  croodles,
  croodlesNeutral,
  dylan,
  funEmoji,
  glass,
  icons,
  identicon,
  initials,
  loreleiNeutral,
  micah,
  miniavs,
  notionists,
  notionistsNeutral,
  openPeeps,
  personas,
  pixelArt,
  pixelArtNeutral,
  rings,
  shapes,
  thumbs,
} from "@dicebear/collection";

export const DOCK_ITEMS = [
  {
    title: "All campaigns",
    icon: Blocks,
    href: "/",
  },
  {
    title: "Add campaign",
    icon: Radio,
    href: "/add-campaign",
  },
  {
    title: "My campaigns",
    icon: User,
    href: "/my-campaigns",
  },
  {
    title: "My donations",
    icon: HandCoins,
    href: "/my-donations",
  },
];
export const AVATARS = [
  lorelei,
  adventurer,
  adventurerNeutral,
  avataaars,
  avataaarsNeutral,
  bigEars,
  bigEarsNeutral,
  bigSmile,
  bottts,
  botttsNeutral,
  croodles,
  croodlesNeutral,
  dylan,
  funEmoji,
  glass,
  icons,
  identicon,
  initials,
  loreleiNeutral,
  micah,
  miniavs,
  notionists,
  notionistsNeutral,
  openPeeps,
  personas,
  pixelArt,
  pixelArtNeutral,
  rings,
  shapes,
  thumbs,
];
